### ISSUE TITLE
Traduire la licence ouverte 2.0 en anglais

### ISSUE THREAD

**Issue by bboulesteix** [etalab/licence-ouverte#1]
[Etalab](https://www.etalab.gouv.fr) met à la disposition du public une licence, qui est notamment utilisée pour les jeux de données publiés par des administrations sur [data.gouv.fr](https://www.data.gouv.fr/fr/), et cette licence, c’est [la Licence Ouverte](https://www.etalab.gouv.fr/licence-ouverte-open-licence) (LO).

La licence ouverte a été publiée dans sa version `1.0` en 2014, [en français](https://www.etalab.gouv.fr/wp-content/uploads/2014/05/Licence_Ouverte.pdf) **et** [en anglais](
https://www.etalab.gouv.fr/wp-content/uploads/2014/05/Open_Licence.pdf). Une mise à jour de la licence ouverte a été rendue publique en 2017, créant ainsi une version `2.0` de la licence, publiée [en français](https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf) **mais pas en anglais** cette fois-ci, semble-t-il — contrairement à ce qui avait été fait pour la version `1.0`. 

Or nous recevons régulièrement des demandes en ce sens, ce qui me fait dire qu’une traduction anglaise de la licence ouverte `2.0` ne ferait pas de mal, en plus d’être cohérent avec ce qui a été fait pour la version `1.0`.

## Questions

Questions pour @mchoquet :

1. Quelles différences entre la version `1.0` et la version `2.0` de la licence ? 🤔 
2. Comment puis-je aider à traduire la version `2.0` de la licence ouverte ? 👋 

Je suppose que si nous repartons de la traduction anglaise effectuée pour la version 1.0, la traduction de la version 2.0 ne devrait pas nous prendre des lustres, mais je me trompe peut-être.

**Comment by Orphanet** [comment]
Bonjour,
Exactement la même problématique dans un contexte de projets internationaux. Où se trouve la LOV2 en anglais ?
Merci.

**Comment by bboulesteix** [comment]
Bonjour @Orphanet, merci pour votre contribution. Pour vous répondre, la licence ouverte `2.0` n’est pour le moment disponible qu’en version française. Il n’existe une traduction anglaise de la licence ouverte que pour la version `1.0`, [la précédente version](
https://www.etalab.gouv.fr/wp-content/uploads/2014/05/Open_Licence.pdf). 

Je ne peux pas vous donner de date de mise en ligne, mais l’existence de cette discussion vous montre que la traduction de la licence ouverte `2.0` est un sujet sur lequel nous avons prévu de travailler chez Etalab. Gardez un œil sur ce dépôt GitHub pour être tenu au courant de nos avancées en la matière — vous trouverez comment faire [sur le site d’aide de GitHub](https://help.github.com/articles/watching-and-unwatching-repositories/) (en anglais).

**Comment by Orphanet** [comment]
(grand) merci de votre retour. effectivement je watche le dépôt.

Question du coup, puisque qu'une version anglaise n'existe pas (et que c'est compliqué dans le cadre de grant ou demande de budget sur des projets européens ou internationaux de se référer à un texte à portée juridique en FR uniquement), est-il possible d'envisager d'indiquer qu'on utilise une CCBY (qui est explicitement pleinement compatible Lov2) en attendant de pouvoir repasser sur une lov2, dans un cadre de recherche scientifique. (et j'avouerais modestement que nos services juridiques sont quelques peu démunis sur cet aspect...)

Thx!

**Comment by bboulesteix** [comment]
C’est moi qui vous remercie @Orphanet. Pour vous répondre à mon tour : ça dépend. Si vous travaillez pour une administration, vous _devez_ utiliser la Licence Ouverte (peu importe sa version). 

Je cite le texte :

> La présente licence a vocation à être utilisée par les administrations pour la réutilisation de leurs informations publiques. 

Dans ces conditions, je vous conseillerais donc d’utiliser la Licence Ouverte `1.0` dans [sa version anglaise](https://www.etalab.gouv.fr/wp-content/uploads/2014/05/Open_Licence.pdf).

Si vous ne travaillez pas pour une administration, je suppose que vous pouvez choisir l’une des licences équivalentes citées dans le texte :

> Elle est notamment compatible avec la version antérieure de la présente licence ainsi qu’ avec les licences « Open Government Licence » (OGL) du Royaume-Uni, « Creative Commons Attribution » (CC-BY) de Creative Commons et « Open Data Commons Attribution » (ODC-BY) de l’Open Knowledge Foundation.

J’ajoute pour conclure que ma réponse n’a pas valeur de conseil juridique.

**Comment by bboulesteix** [comment]
Bonjour @Orphanet, je vous écris pour vous dire que la Licence Ouverte 2.0 est disponible en version anglaise :
* au [format MarkDown](https://github.com/etalab/licence-ouverte/blob/master/open-licence.md) ;
* au [format PDF](https://www.etalab.gouv.fr/wp-content/uploads/2018/11/open-licence.pdf).

**Comment by Orphanet** [comment]
Fantastique! Merci de votre réactivité. 
Ne reste plus qu'à la faire connaître au monde entier.
