### ISSUE TITLE
Tag "License" pour le fichier DEP-5

### ISSUE THREAD

**Issue by MoonSweep** [etalab/licence-ouverte#15]
Bonjour,

Merci d'avoir accepté mes contributions.

Cependant, vous avez remis l'anglais britannique "Licence" au lieu de l'américain "License" ; je comprends tout à fait ce choix, cependant, dans le fichier DEP-5, dans la première ligne, "License:" est un tag.

Merci de corriger la première ligne en : 

`License: OPEN-LICENCE-2.0`

Sans quoi le fichier n'est pas conforme au standard DEP-5 et fait échouer l'analyse du fichier `debian/copyright` par `debhelper`.

**Comment by bzg** [comment]
Merci de votre retour.

Pouvez-vous envoyer une PR pour cette correction ?

**Comment by bzg** [comment]
Merci !

**Comment by markopitko11-jpg** [comment]
> شكراً!

Erour
