### ISSUE TITLE
La non réception du  code 

### ISSUE THREAD

**Issue by AB28890** [etalab/licence-ouverte#8]
J'ai essayé de demander un nouveau code , en utilisent ma boite mail que J'ai remplie  sur https://pastel.diplomatie.gouv.fr/etudesenfrance/dyn/public/reinitialiserMotDePasse.html?sctxid=2-34b1b8604d&_csrf=91d84e9a-d4c4-4a94-82b7-c3e1bcf6406c#yui_3_8_1_1_1679138618598_95

Mais . J'ai rien reçu . Merci de m'aider a trouver une solutio n a fin que je puisse connecter avotre plate-forme . Merci d'avance :)

**Comment by bzg** [comment]
Bonjour, il faut vous adresse au service pertinent, pas ouvrir une issue dans ce dépôt.
